version: '3.8'

services:
  hugo-helper:
    image: ghcr.io/wenwen12345/hugo-helper:latest
    container_name: hugo-helper
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ${HUGO_PATH}:/www/hugo
    networks:
      - hugo-net

networks:
  hugo-net:
    driver: bridge